### PR TITLE
CodeforHamburg update

### PR DESCRIPTION
**Pull request by lundelius**
- new place
- new domain

### CODE REVIEW

**Comment by ondrae** [comment]
You can also use https://github.com/codeforhamburg as the `project_list_url`. Want to use that instead?

**Comment by lundelius** [comment]
Hi Ondrae, 
thank you for the hint but we set it up that way to add their non-hosted or organised projects... especially ideas, meta-projects and goals... etc. 

I hope it will work that way via spreadsheet. 

And off course non-github users are able to add some project(idea)

**Comment by ondrae** [comment]
Hey @lundelius sorry I let this sit for awhile. My fault.

You are live at:
http://www.codeforamerica.org/api/organizations/Code-for-Hamburg
http://www.codeforamerica.org/api/organizations/Code-for-Hamburg/projects
http://www.codeforamerica.org/brigade/projects?q=Code+for+Hamburg
http://www.codeforamerica.org/api/organizations/Code-for-Hamburg/issues
https://www.codeforamerica.org/geeks/civicissues/widget?organization_name=Code-for-Hamburg

**Comment by lundelius** [comment]
Hi,
but thx for doing it now!!

Here is the first result :-)

http://codeforhamburg.org/

Now we fill up the table.

Best
Timo

Am 04/05/16 um 19:44 schrieb Andrew Hyder:

> Hey @lundelius https://github.com/lundelius sorry I let this sit for 
> awhile. My fault.
> 
> You are live at:
> http://www.codeforamerica.org/api/organizations/Code-for-Hamburg
> http://www.codeforamerica.org/api/organizations/Code-for-Hamburg/projects
> http://www.codeforamerica.org/brigade/projects?q=Code+for+Hamburg
> http://www.codeforamerica.org/api/organizations/Code-for-Hamburg/issues
> https://www.codeforamerica.org/geeks/civicissues/widget?organization_name=Code-for-Hamburg
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub 
> https://github.com/codeforamerica/brigade-information/pull/22#issuecomment-216944765

## 

// Timo Lundelius
// timo@lundelius.com
// +49157 82901744
// Eidelstedter Weg 9, 20255 Hamburg, DE
// skype: timo.lundelius
// twitter: @timo_lundelius
// xing.com/profile/Timo_Lundelius
// linkedin.com/pub/timo-lundelius/27/92/8a7/

**Pull request merged**
