### PR TITLE
Add Civic Tech Toronto

### PR DESCRIPTION
**Pull request by patcon**
cc: @alox @gabesawhney

### CODE REVIEW

**Comment by patcon** [comment]
bump?

cc: @therebelrobot Know who's in charge of this project right now? HALP? :)

**Comment by ondrae** [comment]
Oh shoot, my fault @patcon. I went offline for a little bit and missed this.

**Comment by patcon** [comment]
No sweat. Thanks! :)

**Comment by ondrae** [comment]
Okay, you are live:
http://www.codeforamerica.org/brigade/Civic-Tech-Toronto/
http://www.codeforamerica.org/api/organizations/Civic-Tech-Toronto
http://www.codeforamerica.org/brigade/Civic-Tech-Toronto/projects
Once you get some tests on your projects http://www.codeforamerica.org/brigade/Civic-Tech-Toronto/projects/monitor
http://www.codeforamerica.org/geeks/civicissues/widget?organization_name=Civic-Tech-Toronto

**Comment by patcon** [comment]
Correction in #11. Sorry :/

And those links seem to be 404'ing, but I'll assume you're aware

**Comment by ondrae** [comment]
Links should be working again.

**Comment by patcon** [comment]
:heart:

**Pull request merged**
