### PR TITLE
Added Georgia GovTech orgs

### PR DESCRIPTION
**Pull request by Shaunm44**
1) Georgia Tech Authority
2) Digital Services Georgia

### CODE REVIEW

**Comment by tdooner** [comment]
Not to be all nitpicky but the test failure is due to a 2-space (instead of 4-space) indent on the "Government" entry. Not sure why the `bin/format-json` script doesn't work, but it should fix that.

**Comment by Shaunm44** [comment]
No problem being nitpicky - please do to maintain a quality API.

I recognize VSCode was formatting on Save and that's where the unexpected formatting was coming from. Apologies for the mixup, but thanks for your help @tdooner ! 👏🏾

**Comment by Shaunm44** [comment]
Hey @tdooner, just remembered this wasn't closed. Is there anything else I need to do to get it the pull request merged?

**Comment by tdooner** [comment]
Nope, looks great. Thanks!

**Pull request merged**
